contact_links:
  - name: Question
    url: https://github.com/takula-tech/nita-obel/discussions/categories/q-a
    about:
      Questions about how to use or contribute to Obel belong in Github Discussions.
      You can use the search to check if someone already answered your question!
